DOMAIN = "ready4sky"
DEFAULT_INTERFACE = "hci0"
DEFAULT_SCAN_INTERVAL = 30
STRING_HEX_SYMBOLS = '0123456789ABCDEF'
CONF_UNIQUE_ID = 'unique_id'
CONF_BLUETOOTH_FACE_NAME = 'bluetooth_face_name'
CONF_BLUETOOTH_FACE_INDEX = 'bluetooth_face_index'
CONF_MANUFACTURER = 'manufacturer'
CONF_MODEL = 'model'
CONF_NAME = 'name'
CONF_BLUETOOTH_FACE_INDEX = 'bluetooth_face_index'
CONF_TEMPERATURE_LIGHT = 'temperatureLight'
SUPPORTED_PLATFORMS = ["sensor", "light", "switch", "water_heater"]
SUPPORTED_DOMAINS = ["sensor", "light", "switch", "binary_sensor", "water_heater"]
